# Generated by Django 6.0.6 on 2026-06-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0004_auditevent_accepted_relay_urls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiry. Null means the token never expires.', null=True),
        ),
    ]
