# Generated by Django 6.0.6 on 2026-06-20 20:47

from collections import defaultdict

from django.db import migrations, models


VALID = "valid"
GROUP_BATCH_SIZE = 500
EVENT_CHUNK_SIZE = 2_000


def message_id_values(
    msg_id,
    outbound_msg_id,
    invalidated_msg_id,
    outbound_welcome_msg_ids,
    human_action_message_ids,
):
    ids = []
    for value in (msg_id, outbound_msg_id, invalidated_msg_id):
        if value:
            ids.append(value)
    ids.extend(outbound_welcome_msg_ids or [])
    ids.extend(human_action_message_ids or [])
    return ids


def iter_group_id_batches(AuditGroup):
    batch = []
    group_ids = AuditGroup.objects.order_by("id").values_list("id", flat=True)
    for group_id in group_ids.iterator(chunk_size=GROUP_BATCH_SIZE):
        batch.append(group_id)
        if len(batch) == GROUP_BATCH_SIZE:
            yield batch
            batch = []
    if batch:
        yield batch


def divergent_counts_for_group_ids(AuditEvent, group_ids):
    counts = dict.fromkeys(group_ids, 0)
    engines_by_group = defaultdict(set)
    message_engines_by_group = defaultdict(lambda: defaultdict(set))
    rows = AuditEvent.objects.filter(
        group_id__in=group_ids,
        parse_status=VALID,
        audit_file__validation_status=VALID,
    ).values_list(
        "group_id",
        "engine_id",
        "msg_id",
        "outbound_msg_id",
        "invalidated_msg_id",
        "outbound_welcome_msg_ids",
        "human_action_message_ids",
    )

    for (
        group_id,
        engine_id,
        msg_id,
        outbound_msg_id,
        invalidated_msg_id,
        outbound_welcome_msg_ids,
        human_action_message_ids,
    ) in rows.iterator(chunk_size=EVENT_CHUNK_SIZE):
        if not engine_id:
            continue
        engines_by_group[group_id].add(engine_id)
        for message_id in message_id_values(
            msg_id,
            outbound_msg_id,
            invalidated_msg_id,
            outbound_welcome_msg_ids,
            human_action_message_ids,
        ):
            message_engines_by_group[group_id][message_id].add(engine_id)

    for group_id, message_engines in message_engines_by_group.items():
        all_engines = engines_by_group[group_id]
        counts[group_id] = sum(
            1 for engines in message_engines.values() if engines and all_engines.difference(engines)
        )
    return counts


def backfill_divergent_message_counts(apps, _schema_editor):
    AuditEvent = apps.get_model("forensics", "AuditEvent")
    AuditGroup = apps.get_model("forensics", "AuditGroup")

    for group_ids in iter_group_id_batches(AuditGroup):
        counts = divergent_counts_for_group_ids(AuditEvent, group_ids)
        updates = []
        groups = AuditGroup.objects.filter(id__in=group_ids).only(
            "id",
            "divergent_message_count",
        )
        for group in groups.iterator(chunk_size=GROUP_BATCH_SIZE):
            count = counts.get(group.id, 0)
            if group.divergent_message_count != count:
                group.divergent_message_count = count
                updates.append(group)

        if updates:
            AuditGroup.objects.bulk_update(
                updates,
                ["divergent_message_count"],
                batch_size=GROUP_BATCH_SIZE,
            )


def reset_divergent_message_counts(apps, _schema_editor):
    AuditGroup = apps.get_model("forensics", "AuditGroup")
    AuditGroup.objects.update(divergent_message_count=0)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("forensics", "0005_uploadtoken_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditgroup",
            name="divergent_message_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            backfill_divergent_message_counts,
            reset_divergent_message_counts,
        ),
    ]
