# Generated by Django 6.0.6 on 2026-06-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0006_auditgroup_divergent_message_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['line_hash', 'engine_id'], name='forensics_a_line_hash_eng_idx'),
        ),
    ]
