# Generated by Django 6.0.6 on 2026-06-21 18:59

from django.db import migrations, models


THROUGH_BATCH_SIZE = 500
EVENT_CHUNK_SIZE = 2_000


def iter_file_group_links(AuditEvent):
    """Yield distinct (audit_file_id, group_id) pairs derived from stored events.

    Reproduces the OLD ``groups_for_audit_file`` result -- one link per group
    that has at least one stored AuditEvent for a given file -- so existing
    files keep their currently-derived links with no regression.
    """
    rows = (
        AuditEvent.objects.filter(group__isnull=False)
        .values_list("audit_file_id", "group_id")
        .distinct()
        .order_by("audit_file_id", "group_id")
    )
    yield from rows.iterator(chunk_size=EVENT_CHUNK_SIZE)


def backfill_audit_file_groups(apps, _schema_editor):
    # Backfill the explicit AuditFile.groups membership for every existing file
    # from its stored AuditEvent rows. This preserves the current
    # stored-event-derived behavior exactly. NOTE: groups whose events were all
    # deduplicated away in PAST uploads were never stored as AuditEvent rows, so
    # that historical membership is unrecoverable here -- this backfill cannot
    # resurrect it. The fix prevents FUTURE under-reporting by recording the
    # link at ingest time (marmot-protocol/goggles#37).
    AuditEvent = apps.get_model("forensics", "AuditEvent")
    AuditFile = apps.get_model("forensics", "AuditFile")
    Through = AuditFile.groups.through

    batch = []
    for audit_file_id, group_id in iter_file_group_links(AuditEvent):
        batch.append(Through(auditfile_id=audit_file_id, auditgroup_id=group_id))
        if len(batch) == THROUGH_BATCH_SIZE:
            Through.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []
    if batch:
        Through.objects.bulk_create(batch, ignore_conflicts=True)


def clear_audit_file_groups(apps, _schema_editor):
    AuditFile = apps.get_model("forensics", "AuditFile")
    AuditFile.groups.through.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('forensics', '0006_auditgroup_divergent_message_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='audit_files_linked', to='forensics.auditgroup'),
        ),
        migrations.RunPython(
            backfill_audit_file_groups,
            clear_audit_file_groups,
        ),
    ]
