# Generated by Django 6.0.6 on 2026-06-21 20:18

from django.db import migrations, models


def auditevent_line_hash_engine_index():
    return models.Index(fields=['line_hash', 'engine_id'], name='forensics_a_line_hash_eng_idx')


def add_auditevent_line_hash_engine_index(apps, schema_editor):
    AuditEvent = apps.get_model('forensics', 'AuditEvent')
    kwargs = {'concurrently': True} if schema_editor.connection.vendor == 'postgresql' else {}
    schema_editor.add_index(AuditEvent, auditevent_line_hash_engine_index(), **kwargs)


def remove_auditevent_line_hash_engine_index(apps, schema_editor):
    AuditEvent = apps.get_model('forensics', 'AuditEvent')
    kwargs = {'concurrently': True} if schema_editor.connection.vendor == 'postgresql' else {}
    schema_editor.remove_index(AuditEvent, auditevent_line_hash_engine_index(), **kwargs)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('forensics', '0006_auditgroup_divergent_message_count'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # PostgreSQL gets CREATE INDEX CONCURRENTLY so growing AuditEvent
            # tables can continue accepting uploads while the index builds.
            # SQLite test databases use ordinary CREATE INDEX because only the
            # PostgreSQL schema editor accepts the concurrently flag.
            database_operations=[
                migrations.RunPython(
                    add_auditevent_line_hash_engine_index,
                    remove_auditevent_line_hash_engine_index,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='auditevent',
                    index=auditevent_line_hash_engine_index(),
                ),
            ],
        )
    ]
