# Generated by Django 6.0.6 on 2026-06-22 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forensics", "0007_add_auditevent_line_hash_engine_index"),
        ("forensics", "0007_auditfile_groups"),
    ]

    operations = []
