# Generated by Django 6.0.6 on 2026-06-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0010_recompute_divergent_counts_partial_invalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvergenceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.CharField(max_length=256)),
                ('fork_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tip_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('commit_ids', models.JSONField(blank=True, default=list)),
                ('commit_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('state_digest', models.CharField(blank=True, max_length=64)),
                ('tip_digest', models.CharField(blank=True, max_length=64)),
                ('tip_priority', models.CharField(blank=True, max_length=80)),
                ('tip_committer_ref', models.CharField(blank=True, max_length=32)),
                ('tip_committer_pubkey_hex', models.CharField(blank=True, max_length=64)),
                ('retained_anchor_status', models.CharField(blank=True, max_length=120)),
                ('last_input_time_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('eligible', models.BooleanField(blank=True, null=True)),
                ('rejection_reasons', models.JSONField(blank=True, default=list)),
                ('score', models.JSONField(blank=True, default=dict)),
                ('app_witnesses', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['run_id', 'fork_epoch', 'tip_epoch', 'branch_id'],
            },
        ),
        migrations.CreateModel(
            name='ConvergenceRuleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=160)),
                ('scope', models.CharField(blank=True, max_length=80)),
                ('candidate_branch_id', models.CharField(blank=True, max_length=256)),
                ('other_candidate_branch_id', models.CharField(blank=True, max_length=256)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('decisive', models.BooleanField(default=False)),
                ('selected_branch_id', models.CharField(blank=True, max_length=256)),
                ('rejected_branch_id', models.CharField(blank=True, max_length=256)),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['run_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConvergenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=160)),
                ('engine_id', models.CharField(max_length=64)),
                ('account_ref', models.CharField(blank=True, max_length=64)),
                ('inferred', models.BooleanField(default=False)),
                ('phase', models.CharField(blank=True, max_length=80)),
                ('started_at_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ended_at_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('current_tip_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('selected_branch_id', models.CharField(blank=True, max_length=256)),
                ('selected_fork_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('selected_tip_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_rewind_commits', models.PositiveBigIntegerField(blank=True, null=True)),
                ('losing_branch_ids', models.JSONField(blank=True, default=list)),
                ('error_kinds', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['started_at_ms', 'engine_id', 'run_id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.TextField()),
                ('artifact_kind', models.CharField(blank=True, max_length=80)),
                ('first_seen_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_seen_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('audit_data_modes', models.JSONField(blank=True, default=list)),
                ('author', models.JSONField(blank=True, default=dict)),
                ('decoded_payload', models.JSONField(blank=True, default=dict)),
                ('decoded_app_event', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['first_seen_ms', 'artifact_id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_id', models.CharField(max_length=64)),
                ('account_ref', models.CharField(blank=True, max_length=64)),
                ('first_seen_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_seen_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('states', models.JSONField(blank=True, default=list)),
                ('latest_state', models.CharField(blank=True, max_length=120)),
                ('missing_inferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['artifact_id', 'engine_id'],
            },
        ),
        migrations.CreateModel(
            name='EpochStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_id', models.CharField(max_length=64)),
                ('account_ref', models.CharField(blank=True, max_length=64)),
                ('previous_state', models.CharField(blank=True, max_length=120)),
                ('new_state', models.CharField(max_length=120)),
                ('epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('pending_ref', models.PositiveBigIntegerField(blank=True, null=True)),
                ('pending_kind', models.CharField(blank=True, max_length=120)),
                ('wall_time_ms', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['wall_time_ms', 'engine_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=40)),
                ('phase', models.CharField(max_length=80)),
                ('message_id', models.TextField(blank=True)),
                ('artifact_kind', models.CharField(blank=True, max_length=80)),
                ('engine_id', models.CharField(blank=True, max_length=64)),
                ('account_ref', models.CharField(blank=True, max_length=64)),
                ('wall_time_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('transport_source', models.CharField(blank=True, max_length=80)),
                ('delivery_plane', models.CharField(blank=True, max_length=80)),
                ('relay_url', models.TextField(blank=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255)),
                ('wire_id', models.TextField(blank=True)),
                ('wire_kind', models.CharField(blank=True, max_length=80)),
                ('wire_pubkey_hex', models.CharField(blank=True, max_length=64)),
                ('transport_group_id', models.TextField(blank=True)),
                ('nostr_event_id', models.CharField(blank=True, max_length=64)),
                ('nostr_kind', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nostr_pubkey_hex', models.CharField(blank=True, max_length=64)),
                ('gift_wrap_event_id', models.CharField(blank=True, max_length=64)),
                ('welcome_nostr_event_id', models.CharField(blank=True, max_length=64)),
                ('welcome_rumor_event_id', models.CharField(blank=True, max_length=64)),
                ('welcome_key_package_tag', models.TextField(blank=True)),
                ('publish_result_id', models.CharField(blank=True, max_length=255)),
                ('payload_len', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload_digest', models.CharField(blank=True, max_length=128)),
                ('outcome', models.CharField(blank=True, max_length=120)),
                ('accepted_relay_urls', models.JSONField(blank=True, default=list)),
                ('failed_relays', models.JSONField(blank=True, default=list)),
                ('required_acks', models.PositiveIntegerField(blank=True, null=True)),
                ('met_required_acks', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['wall_time_ms', 'engine_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipientExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_kind', models.CharField(blank=True, max_length=80)),
                ('recipient_scope', models.CharField(max_length=80)),
                ('membership_epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('basis_commit_id', models.TextField(blank=True)),
                ('expected_member_refs', models.JSONField(blank=True, default=list)),
                ('expected_pubkeys_hex', models.JSONField(blank=True, default=list)),
                ('expected_count', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['artifact_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StateDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.PositiveBigIntegerField(blank=True, null=True)),
                ('change_kind', models.CharField(max_length=120)),
                ('membership_change_source', models.CharField(blank=True, max_length=80)),
                ('actor_member_ref', models.CharField(blank=True, max_length=32)),
                ('actor_pubkey_hex', models.CharField(blank=True, max_length=64)),
                ('subject_member_ref', models.CharField(blank=True, max_length=32)),
                ('subject_pubkey_hex', models.CharField(blank=True, max_length=64)),
                ('origin_commit_id', models.TextField(blank=True)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('component_ids', models.JSONField(blank=True, default=list)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('audit_data_mode', models.CharField(blank=True, max_length=80)),
                ('wall_time_ms', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['epoch', 'wall_time_ms', 'id'],
            },
        ),
        migrations.AddField(
            model_name='auditevent',
            name='audit_data_mode',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='context_convergence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='context_source',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='recorder_session_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='audit_data_modes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='source_account_npub',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='source_account_pubkey_hex',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='source_device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='source_device_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditfile',
            name='source_upload_trigger',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['audit_data_mode'], name='forensics_a_audit_d_057756_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['recorder_session_id'], name='forensics_a_recorde_df68bf_idx'),
        ),
        migrations.AddField(
            model_name='convergencerun',
            name='evidence_events',
            field=models.ManyToManyField(related_name='convergence_run_evidence', to='forensics.auditevent'),
        ),
        migrations.AddField(
            model_name='convergencerun',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convergence_runs', to='forensics.auditgroup'),
        ),
        migrations.AddField(
            model_name='convergenceruleevaluation',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_evaluations', to='forensics.convergencerun'),
        ),
        migrations.AddField(
            model_name='convergencecandidate',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='forensics.convergencerun'),
        ),
        migrations.AddField(
            model_name='deliveryartifact',
            name='evidence_events',
            field=models.ManyToManyField(related_name='delivery_artifact_evidence', to='forensics.auditevent'),
        ),
        migrations.AddField(
            model_name='deliveryartifact',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_artifacts', to='forensics.auditgroup'),
        ),
        migrations.AddField(
            model_name='deliveryobservation',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_observations', to='forensics.deliveryartifact'),
        ),
        migrations.AddField(
            model_name='deliveryobservation',
            name='evidence_events',
            field=models.ManyToManyField(related_name='delivery_observation_evidence', to='forensics.auditevent'),
        ),
        migrations.AddField(
            model_name='epochstatetransition',
            name='audit_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epoch_state_transitions', to='forensics.auditevent'),
        ),
        migrations.AddField(
            model_name='epochstatetransition',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epoch_state_transitions', to='forensics.auditgroup'),
        ),
        migrations.AddField(
            model_name='networkobservation',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_observations', to='forensics.deliveryartifact'),
        ),
        migrations.AddField(
            model_name='networkobservation',
            name='audit_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_observations', to='forensics.auditevent'),
        ),
        migrations.AddField(
            model_name='networkobservation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_observations', to='forensics.auditgroup'),
        ),
        migrations.AddField(
            model_name='recipientexpectation',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_expectations', to='forensics.deliveryartifact'),
        ),
        migrations.AddField(
            model_name='recipientexpectation',
            name='evidence_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_expectations', to='forensics.auditevent'),
        ),
        migrations.AddField(
            model_name='statedelta',
            name='audit_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_deltas', to='forensics.auditevent'),
        ),
        migrations.AddField(
            model_name='statedelta',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_deltas', to='forensics.auditgroup'),
        ),
        migrations.AddIndex(
            model_name='convergencerun',
            index=models.Index(fields=['group', 'phase'], name='forensics_c_group_i_19389a_idx'),
        ),
        migrations.AddIndex(
            model_name='convergencerun',
            index=models.Index(fields=['engine_id', 'started_at_ms'], name='forensics_c_engine__2633da_idx'),
        ),
        migrations.AddConstraint(
            model_name='convergencerun',
            constraint=models.UniqueConstraint(fields=('group', 'engine_id', 'run_id'), name='unique_convergence_run_per_engine'),
        ),
        migrations.AddIndex(
            model_name='convergenceruleevaluation',
            index=models.Index(fields=['rule_name'], name='forensics_c_rule_na_1d0acd_idx'),
        ),
        migrations.AddIndex(
            model_name='convergenceruleevaluation',
            index=models.Index(fields=['decisive'], name='forensics_c_decisiv_3ff6a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='convergencecandidate',
            constraint=models.UniqueConstraint(fields=('run', 'branch_id'), name='unique_convergence_candidate_per_run'),
        ),
        migrations.AddIndex(
            model_name='deliveryartifact',
            index=models.Index(fields=['group', 'artifact_kind'], name='forensics_d_group_i_bc3bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryartifact',
            index=models.Index(fields=['artifact_id'], name='forensics_d_artifac_a6a19c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryartifact',
            index=models.Index(fields=['first_seen_ms'], name='forensics_d_first_s_b27f6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryartifact',
            constraint=models.UniqueConstraint(fields=('group', 'artifact_id'), name='unique_delivery_artifact_per_group'),
        ),
        migrations.AddIndex(
            model_name='deliveryobservation',
            index=models.Index(fields=['engine_id', 'latest_state'], name='forensics_d_engine__d7342a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryobservation',
            index=models.Index(fields=['first_seen_ms'], name='forensics_d_first_s_7297f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryobservation',
            constraint=models.UniqueConstraint(fields=('artifact', 'engine_id'), name='unique_delivery_observation_per_engine'),
        ),
        migrations.AddIndex(
            model_name='epochstatetransition',
            index=models.Index(fields=['group', 'epoch'], name='forensics_e_group_i_ca4462_idx'),
        ),
        migrations.AddIndex(
            model_name='epochstatetransition',
            index=models.Index(fields=['engine_id', 'wall_time_ms'], name='forensics_e_engine__ad8404_idx'),
        ),
        migrations.AddIndex(
            model_name='epochstatetransition',
            index=models.Index(fields=['new_state'], name='forensics_e_new_sta_9b880b_idx'),
        ),
        migrations.AddIndex(
            model_name='networkobservation',
            index=models.Index(fields=['group', 'phase'], name='forensics_n_group_i_0e327b_idx'),
        ),
        migrations.AddIndex(
            model_name='networkobservation',
            index=models.Index(fields=['message_id'], name='forensics_n_message_4fc6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='networkobservation',
            index=models.Index(fields=['engine_id', 'wall_time_ms'], name='forensics_n_engine__e2302c_idx'),
        ),
        migrations.AddIndex(
            model_name='networkobservation',
            index=models.Index(fields=['nostr_event_id'], name='forensics_n_nostr_e_228d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='networkobservation',
            index=models.Index(fields=['relay_url'], name='forensics_n_relay_u_42ccb1_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientexpectation',
            index=models.Index(fields=['recipient_scope'], name='forensics_r_recipie_c46547_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientexpectation',
            index=models.Index(fields=['membership_epoch'], name='forensics_r_members_6a4928_idx'),
        ),
        migrations.AddIndex(
            model_name='statedelta',
            index=models.Index(fields=['group', 'epoch'], name='forensics_s_group_i_1ec2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='statedelta',
            index=models.Index(fields=['change_kind'], name='forensics_s_change__f53076_idx'),
        ),
        migrations.AddIndex(
            model_name='statedelta',
            index=models.Index(fields=['origin_commit_id'], name='forensics_s_origin__d1ee23_idx'),
        ),
    ]
