# Generated by Django 6.0.6 on 2026-06-24 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0011_convergencecandidate_convergenceruleevaluation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='title',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
