# Generated by Django 6.0.7 on 2026-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0013_personalaccesstoken'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditgroup',
            index=models.Index(fields=['-updated_at', 'id'], name='forensics_a_updated_8f04c0_idx'),
        ),
    ]
