# Generated by Django 6.1.1 on 2026-09-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0013_personalaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('too_large', 'Body exceeds the upload size limit'), ('too_many_parts', 'Multipart body carries more than one file part'), ('incomplete_body', 'Body shorter than its Content-Length'), ('length_required', 'Content-Length header missing')], max_length=32)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('declared_content_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('received_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('group_slug', models.CharField(blank=True, max_length=160)),
                ('source_device_label', models.CharField(blank=True, max_length=255)),
                ('source_platform', models.CharField(blank=True, max_length=120)),
                ('source_app_version', models.CharField(blank=True, max_length=120)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to='forensics.uploadtoken')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='forensics_u_created_b52466_idx'), models.Index(fields=['reason'], name='forensics_u_reason_532179_idx')],
            },
        ),
    ]
