# Generated by Django 6.1.1 on 2026-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0014_uploadrejection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditfile',
            name='source_account_label',
        ),
        migrations.RemoveField(
            model_name='auditfile',
            name='source_account_npub',
        ),
        migrations.RemoveField(
            model_name='auditfile',
            name='source_account_pubkey_hex',
        ),
        migrations.RemoveField(
            model_name='auditfile',
            name='source_device_label',
        ),
        migrations.RemoveField(
            model_name='auditfile',
            name='source_device_name',
        ),
        migrations.RemoveField(
            model_name='uploadrejection',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='uploadrejection',
            name='group_slug',
        ),
        migrations.RemoveField(
            model_name='uploadrejection',
            name='source_app_version',
        ),
        migrations.RemoveField(
            model_name='uploadrejection',
            name='source_device_label',
        ),
        migrations.RemoveField(
            model_name='uploadrejection',
            name='source_ip',
        ),
        migrations.RemoveField(
            model_name='uploadrejection',
            name='source_platform',
        ),
        migrations.RemoveField(
            model_name='uploadrejection',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='auditfile',
            name='source_hardware_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadrejection',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadrejection',
            name='reason',
            field=models.CharField(max_length=40),
        ),
    ]
