# Generated by Django 6.1.1 on 2026-09-11 16:50

from django.db import migrations, models


def _indexes():
    return (
        (
            "AuditEvent",
            models.Index(
                fields=["group", "parse_status", "wall_time_ms", "engine_id", "line_number"],
                name="forensics_a_grp_stat_time_idx",
            ),
        ),
        (
            "DeliveryArtifact",
            models.Index(
                fields=["group", "first_seen_ms", "artifact_id"],
                name="forensics_d_grp_seen_idx",
            ),
        ),
        (
            "NetworkObservation",
            models.Index(
                fields=["group", "wall_time_ms", "engine_id"],
                name="forensics_n_grp_time_idx",
            ),
        ),
        (
            "ConvergenceRun",
            models.Index(
                fields=["group", "started_at_ms", "engine_id"],
                name="forensics_c_grp_start_idx",
            ),
        ),
        (
            "StateDelta",
            models.Index(
                fields=["group", "epoch", "wall_time_ms"],
                name="forensics_s_grp_epoch_time_idx",
            ),
        ),
        (
            "EpochStateTransition",
            models.Index(
                fields=["group", "wall_time_ms", "engine_id"],
                name="forensics_e_grp_time_idx",
            ),
        ),
    )


def add_group_time_indexes(apps, schema_editor):
    kwargs = {"concurrently": True} if schema_editor.connection.vendor == "postgresql" else {}
    for model_name, index in _indexes():
        schema_editor.add_index(apps.get_model("forensics", model_name), index, **kwargs)


def remove_group_time_indexes(apps, schema_editor):
    kwargs = {"concurrently": True} if schema_editor.connection.vendor == "postgresql" else {}
    for model_name, index in _indexes():
        schema_editor.remove_index(apps.get_model("forensics", model_name), index, **kwargs)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("forensics", "0015_remove_auditfile_source_account_label_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_group_time_indexes, remove_group_time_indexes),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="auditevent",
                    index=models.Index(
                        fields=[
                            "group",
                            "parse_status",
                            "wall_time_ms",
                            "engine_id",
                            "line_number",
                        ],
                        name="forensics_a_grp_stat_time_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="deliveryartifact",
                    index=models.Index(
                        fields=["group", "first_seen_ms", "artifact_id"],
                        name="forensics_d_grp_seen_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="networkobservation",
                    index=models.Index(
                        fields=["group", "wall_time_ms", "engine_id"],
                        name="forensics_n_grp_time_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="convergencerun",
                    index=models.Index(
                        fields=["group", "started_at_ms", "engine_id"],
                        name="forensics_c_grp_start_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="statedelta",
                    index=models.Index(
                        fields=["group", "epoch", "wall_time_ms"],
                        name="forensics_s_grp_epoch_time_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="epochstatetransition",
                    index=models.Index(
                        fields=["group", "wall_time_ms", "engine_id"],
                        name="forensics_e_grp_time_idx",
                    ),
                ),
            ],
        )
    ]
