# Generated by Django 6.1.1 on 2026-09-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0016_group_time_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['group', 'parse_status', 'schema_version', 'engine_id', 'account_ref', 'recorder_session_id', 'audit_file'], name='goggles_group_sessions_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(condition=models.Q(('context_source', {}), _negated=True), fields=['engine_id', 'account_ref', 'recorder_session_id'], name='goggles_session_source_idx'),
        ),
    ]
