# Generated by Django 6.1.1 on 2026-09-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forensics", "0017_index_source_metadata_lookups"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditfile",
            name="source_local_member_ref",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
